my_string = input( 'напишите произвольный текст: ')
len(my_string)
print ('количество символов в строке выше =  ' , len(my_string))
print('Ваш текст в верхнем регистре выглядит так:', my_string .upper())
print('ваш текст в нижнем регистре выглядит так:',my_string .lower())
print('ваш текст без пробелов выглядит так:',my_string .replace(" ",""))
print('первый символ в Вашем тексте:',my_string[0])
print('последний символ в Вашем тексте:',my_string[-1])